---
application:
  name: "elizatest"
  project: "o"
  organization: "QoveryCommunity"
  storage:
  - name: "Eliza"
    size: "500"
    type: "slow_hdd"
    mount_point: "/mnt/Eliza"
routers:
- name: "main-elizatest"
  routes:
  - application_name: "elizatest"
    paths:
    - "/*"
