---
application:
  name: "elizatest"
  project: "elisa Test"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "Eliza"
  version: "5.6"
routers:
- name: "main-elizatest"
  routes:
  - application_name: "elizatest"
    paths:
    - "/*"
